x-coral-config:
  &coral-config
  network_mode: host
  ipc: host
  tty: true
  environment:
    - ROS_DOMAIN_ID=65
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=/ws/cyclonedds.xml
    - AGENT=doosan
    - PARAMS=/ws/params.yaml
    - BT_FILE=/ws/bt.xml
    - LOADING_LIBRARY_PATH=/ws/lib
  volumes:
    - .:/ws

services:
  doosan_driver:
    image: doosan_deploy:latest
    <<: *coral-config
    profiles: [drivers]

  lidar_driver:
    image: coral-ouster_driver:humble-amd64
    <<: *coral-config
    profiles: [drivers]

  camera_driver:
    image: coral-realsense_driver:humble-amd64
    <<: *coral-config
    volumes:
      - .:/ws
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/video6:/dev/video6
      - /dev/video7:/dev/video7
      - /dev/video8:/dev/video8
      - /dev/video9:/dev/video9
    profiles: [drivers]

  micro_ros:
    image: coral-micro_ros_agent:humble-amd64
    <<: *coral-config
    profiles: [drivers]

  raw_data_server:
    image: coral-watertender:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  slam_server:
    image: coral-hyla_slam:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  image_processing_server:
    image: coral-corrosion_detector:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  data_fusion_server:
    image: coral-phidias:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  file_server:
    image: coral-file_relay:humble-amd64
    <<: *coral-config
    profiles: [skillsets]
  
  point_cloud_processing_server:
    image: coral-point_cloud_processor:humble-amd64
    <<: *coral-config
    profiles: [skillsets]
  
  coverage_plan_server:
    image: coral-magellan:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  nbv_server:
    image: coral-next_best_view:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  primary_executor:
    image: coral-dynamic_runner:humble-amd64
    <<: *coral-config
    profiles: [executors]
