x-coral-config:
  &coral-config
  network_mode: host
  ipc: host
  tty: true
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROS_LOCALHOST_ONLY=1
    - PARAMS=/ws/params.yaml
    - BT_FILE=/ws/bt.xml
    - LOADING_LIBRARY_PATH=/ws/lib
    - BAG_DIR=/ws/bags
    - BAG=colosseo_test0_00
  volumes:
    - .:/ws

services:
  bag_player:
    image: swanbeck/coral-bag_player:humble-amd64
    <<: *coral-config
    profiles: [drivers]

  hyla_slam:
    image: swanbeck/coral-hyla_slam:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  watertender:
    image: swanbeck/coral-watertender:humble-amd64
    <<: *coral-config
    profiles: [skillsets]

  runner:
    image: swanbeck/coral-dynamic_runner:humble-amd64
    <<: *coral-config
    profiles: [executors]
